package com.lianggao.bean;

import java.io.Serializable;

public class Application implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.DangerTaskId
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    private Integer dangerTaskId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.DangerTaskName
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    private String dangerTaskName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.Applicant
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    private Integer applicant;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.StartTime
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    private String startTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.EndTime
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    private String endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.FileName
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column application.State
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    private Integer state;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.DangerTaskId
     *
     * @return the value of application.DangerTaskId
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public Integer getDangerTaskId() {
        return dangerTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.DangerTaskId
     *
     * @param dangerTaskId the value for application.DangerTaskId
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public void setDangerTaskId(Integer dangerTaskId) {
        this.dangerTaskId = dangerTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.DangerTaskName
     *
     * @return the value of application.DangerTaskName
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public String getDangerTaskName() {
        return dangerTaskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.DangerTaskName
     *
     * @param dangerTaskName the value for application.DangerTaskName
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public void setDangerTaskName(String dangerTaskName) {
        this.dangerTaskName = dangerTaskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.Applicant
     *
     * @return the value of application.Applicant
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public Integer getApplicant() {
        return applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.Applicant
     *
     * @param applicant the value for application.Applicant
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public void setApplicant(Integer applicant) {
        this.applicant = applicant;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.StartTime
     *
     * @return the value of application.StartTime
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public String getStartTime() {
        return startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.StartTime
     *
     * @param startTime the value for application.StartTime
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.EndTime
     *
     * @return the value of application.EndTime
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public String getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.EndTime
     *
     * @param endTime the value for application.EndTime
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.FileName
     *
     * @return the value of application.FileName
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.FileName
     *
     * @param fileName the value for application.FileName
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column application.State
     *
     * @return the value of application.State
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column application.State
     *
     * @param state the value for application.State
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public void setState(Integer state) {
        this.state = state;
    }

    @Override
    public String toString() {
        return "Application{" +
                "dangerTaskId=" + dangerTaskId +
                ", dangerTaskName='" + dangerTaskName + '\'' +
                ", applicant=" + applicant +
                ", startTime='" + startTime + '\'' +
                ", endTime='" + endTime + '\'' +
                ", fileName='" + fileName + '\'' +
                ", state=" + state +
                '}';
    }
}