package com.lianggao.bean;

public class UserInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.UserId
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.UserName
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column userinfo.UserPassword
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    private String userPassword;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.UserId
     *
     * @return the value of userinfo.UserId
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.UserId
     *
     * @param userId the value for userinfo.UserId
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.UserName
     *
     * @return the value of userinfo.UserName
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.UserName
     *
     * @param userName the value for userinfo.UserName
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column userinfo.UserPassword
     *
     * @return the value of userinfo.UserPassword
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public String getUserPassword() {
        return userPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column userinfo.UserPassword
     *
     * @param userPassword the value for userinfo.UserPassword
     *
     * @mbggenerated Tue Mar 16 22:11:30 CST 2021
     */
    public void setUserPassword(String userPassword) {
        this.userPassword = userPassword;
    }

    @Override
    public String toString() {
        return "UserInfo{" +
                "userId=" + userId +
                ", userName='" + userName + '\'' +
                ", userPassword='" + userPassword + '\'' +
                '}';
    }
}